/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class IntegralSampleTest {
    @Test public void restResult() {
        IntegralSample classUnderTest = new IntegralSample();
        double result = classUnderTest.calculate();
        System.out.println(result);
        assertTrue(result > 16.6 && result < 16.7);
    }
}
