{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7-rc-1",
      "buildId": "5sxviip6zzarnonuq2yfpklpci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 5755,
          "sha512": "49373e13924257c92732e381d6a3374031428da6b0c8eb34d8f394ca2c2285adfbc1b79e06c5373314a5b0ffe75c60ada70688d2baac1552e6bc8fe2516b47e9",
          "sha256": "1d13f61341b73875fb7ea3e2928d082b8c4ff0392ac84761a5354d9216b3ac12",
          "sha1": "19a6c57c3c94af3e4c8389e6f2c6bfcd1b9751d2",
          "md5": "39ffdc2b06191e3ded9292307b213fb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.3.72"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 5755,
          "sha512": "49373e13924257c92732e381d6a3374031428da6b0c8eb34d8f394ca2c2285adfbc1b79e06c5373314a5b0ffe75c60ada70688d2baac1552e6bc8fe2516b47e9",
          "sha256": "1d13f61341b73875fb7ea3e2928d082b8c4ff0392ac84761a5354d9216b3ac12",
          "sha1": "19a6c57c3c94af3e4c8389e6f2c6bfcd1b9751d2",
          "md5": "39ffdc2b06191e3ded9292307b213fb1"
        }
      ]
    }
  ]
}
